import Navbar from "@/components/Navbar";
import "./globals.css";
import "@fontsource/montserrat";
import Footer from "@/components/Footer";

export const metadata = {
  title: "CMX Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://api.fontshare.com/v2/css?f[]=instrument-sans@400,700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <Navbar />
        <div className="flex items-center justify-center bg-primary">
          <h1 className="text-lg py-4">18th January, 2024</h1>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
